name: deploy_workflow
on:
  push:
    branches:
      - master

jobs:
  deploy-android-customer:
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.18.0-11.1.pre"
          channel: "beta"
      - run: flutter config --enable-web
      - run: flutter build apk --split-per-abi --target lib/main.dart --debug
